name: Pipeline 2 - Platform Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: read
  security-events: write

jobs:

  deploy-platform:

    runs-on:
      - self-hosted
      - Linux
      - X64
    env:
      # Config Server credentials
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      
      # Vault
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_PORT: ${{ secrets.VAULT_PORT }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      #######################################################
      # Deploy Infrastructure
      #######################################################

      - name: Deploy Infrastructure
        run: |
          docker compose \
            --env-file compose/.env \
            --env-file compose/versions.env \
            -f compose/infrastructure.yml \
            up -d

      - name: Wait for Infrastructure
        run: sleep 60

      #######################################################
      # Deploy Platform
      #######################################################
      - name: Deploy Platform
        run: |
          docker compose \
            --env-file compose/.env \
            --env-file compose/versions.env \
            -f compose/platform.yml \
            up -d

      - name: Wait for Platform
        run: sleep 150
      
      - name: Test Config Server Before Apps
        run: |
          curl http://localhost:8888/service-user/default
          curl http://localhost:8888/actuator/health

      #######################################################
      # Deploy Applications
      #######################################################
      

      - name: Deploy Applications
        run: |
          docker compose \
            --env-file compose/.env \
            --env-file compose/versions.env \
            -f compose/application.yml \
            up -d

      - name: Wait for Applications
        run: sleep 60

      #######################################################
      # Deploy Monitoring
      #######################################################

      - name: Deploy Monitoring
        run: |
          docker compose \
            --env-file compose/.env \
            --env-file compose/versions.env \
            -f compose/monitoring.yml \
            up -d

      - name: Wait for Monitoring
        run: sleep 60

      #######################################################
      # Health Checks
      #######################################################

      - name: Verify Running Containers
        run: docker ps
      
      #######################################################
      # OWASP ZAP
      ####################################################### 
      - name: Test Gateway
        run: |
          curl -v http://localhost:8880/actuator/health

      - name: Run ZAP
        run: |
          docker run --rm \
            --network=host \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8880 \
            -r report.html \
            -J report.json \
            -w report.md \
            -x report.xml

      - name: Verify reports
         run: ls -lah report*

      #######################################################
      # Upload Reports
      #######################################################

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report.html
            report.json
            report.md
            report.xml